version: "3.8"

services:

  mysql_db:
    image: mysql:8.0.36
    container_name: vacaciones_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: sistema_vacaciones
      MYSQL_USER: vacaciones_user
      MYSQL_PASSWORD: vacaciones_pass
    ports:
      - "3308:3306"
    volumes:
      - vacaciones_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  api:
    image: openjdk:17-jdk-slim
    container_name: vacaciones_api
    restart: always
    working_dir: /app
    volumes:
      - ./target/app.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8090:8080"
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/sistema_vacaciones
      SPRING_DATASOURCE_USERNAME: vacaciones_user
      SPRING_DATASOURCE_PASSWORD: vacaciones_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  vacaciones_mysql_data:
